name: Docker Compose Action

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - name: Run docker-compose
      #   uses: hoverkraft-tech/compose-action@v2.0.1
      #   with:
      #     compose-file: "./compose.yaml"

      # - name: Execute tests in the running services
      #   run: |
      #     docker compose up

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/matv864/smm_shelter
            sudo git pull
            sudo docker stop
            sudo docker rm -f smm_shelter-backend smm_shelter-frontend smm_shelter-postgres smm_shelter-nginx
            sudo docker compose up -d
